##
# DynamicMarket V0.6.1
##
general:
    # Whether or not a player can make a purchase while holding an item
    empty-hand-required: false
    # Shop tag is what is displayed before most shop output  Default is [Shop].  Improved coloring system coming soon
    shop-tag: '{BKT}[{}Shop{BKT}]{} '
    transactions:
        # Whether or not shop transactions should be logged
        log-transactions: false
        # The file to log transactions in (located in plugins/DynamicMarket)
        log-file: transactions.log
        # If true the file will save after every transaction.  If false the file will save on server shutdown
        log-auto-flush: true
        # Maximum number of items (not bundles) a user is allowed to buy in one transaction
        max-items-buy: 64
        # Maximum number of items (not bundles) a user is allowed to sell in one transaction
        max-items-sell: 64
    csv:
        # The file to export/import shop data to/from.
        file: shopexport.csv
    shop-account:
        # Whether or not sales that would put the shop account below 0 money can be made
        free: true
        # The name of the shop's economy account (blank = no shop account)
        name: ''
database:
    # Database type, either sqlite or mysql
    type: sqlite
    sqlite:
        # The file to store an sqlite database in (lcoated in plugins/DynamicMarket)
        file: shop.db
    mysql:
        # URI for your mysql database
        database: jdbc:mysql://localhost:3306/minecraft
        # MySQL username
        user: root
        # MySQL password
        password: pass
        # MySQL database engine (recommended MyISAM)
        engine: MyISAM
permissions:
    # If set to true DynamicMarket will ignore the permissions plugin
    # Regular users get 'dynamicmarket.access', 'dynamicmarket.buy', and 'dynamicmarket.sell'
    ignore-permissions: false
    # Whether or not ops should get all permissions
    op-permissions: false