name: DynamicMarket
main: com.goalieguy6.dynamicmarket.DynamicMarket
version: ${project.version}
author: GoalieGuy6
description: A shop plugin with live updating prices based on supply and demand.
commands:
    dynamicmarket:
        description: Access the shop
        aliases: [dm, shop]
        usage: |
               /<command>
